name: IfExec
main: com.ifexec.IfExec
version: 1.0.0
api-version: 1.20
authors: ["IfExecAuthor"]
commands:
  if:
    description: Create and manage conditional triggers
    aliases: [triggerif, cond]
    usage: /if
    permission: ifexec.use
    permission-message: "&cYou don't have permission to use IfExec."
permissions:
  ifexec.use:
    description: Use basic IfExec commands
    default: true
  ifexec.admin:
    description: Admin commands for IfExec
    default: op
  ifexec.staff:
    description: Marks a player as staff for staff-only triggers
    default: false
